apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: q2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q2
    app.kubernetes.io/part-of: q2
  name: q2
  namespace: gazarenk
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: q2
    weight: 100
status: {}
